###############################################################################
## EXAMPLE 1: How to conduct the Mann-Whitney U test and Brunner-Munzel test
## From Tomek & Eisner: Basic Statistics for Life Scientists. https://github.com/jtmff/stats_BSfLS
###############################################################################
library(ggplot2)
library(brunnermunzel)

set.seed(321) # Fixed random number generator seed for reproducibility

# We generate two groups of non-normally distributed data
data_A <- rexp(15, rate = 1)  # Exponential distribution to introduce skewness
data_B <- 0.5 + rexp(15, rate = 0.5)  

# Combine data into a data frame
df <- data.frame(
  value = c(data_A, data_B),
  group = factor(c(rep("A", length(data_A)), rep("B", length(data_B))))
)

# Plot the data, note the non-normal shape.
ggplot(df, aes(x = group, y = value)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center') +
  theme_minimal() +
  labs(x = "Group",
       y = "Value")

# Perform the Mann-Whitney U test and print the results
test_result <- wilcox.test(value ~ group, data = df)
print(test_result) # The p-value is ca. 0.0145

# You can also run the test without storing the data in a dataframe, 
# using the first two parameters to provide the sets of numbers.
test_result_2 <- wilcox.test(data_A, data_B)
print(test_result_2$p.value) # The p-value is ca. 0.0145

# Running the Brunner-Munzel test (permutation version can be obtained
# by setting the parameter perm = TRUE)
test_BM_result <- brunnermunzel.test(value ~ group, data = df)
print(test_BM_result$p.value) # The p-value is ca. 0.008
# For few points per group (e.g. <10), it is better to use the permutation version
# of the test.

# We can also calculate the Welch t-test for comparison
results_welch <- t.test(data_A, data_B, var.equal = FALSE)
print(results_welch$p.value) # The p-value is ca. 0.0695
# The p-value generated by the t-test is substantially higher and would not be statistically significant at the 0.05 level. 
# This illustrates limitations of the common statement "parametric tests are more powerful than nonparametric". A t-test will be slightly more powerful than Mann-Whitney U test, when the assumptions of the t-test hold, but the situation can be the opposite when the assumptions are violated.